---
abstract: 'Select a pager and pipe text to it if destination is a TTY'
author:
  - 'Jerrad Pierce <jpierce@cpan.org>, Florent Angly <florent.angly@gmail.com>'
build_requires:
  Config: '0'
  Env: '0'
  Exporter: '0'
  File::Temp: '0'
  Test::More: '0.88'
  bignum: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Pager
no_index:
  directory:
    - t
    - inc
requires:
  Env: '0'
  File::Spec: '0'
  File::Which: '0'
  IO::Handle: '0'
  PerlIO: '0'
  SelectSaver: '0'
  Symbol: '0'
  Term::ReadKey: '0'
  Text::Wrap: '0'
  Tie::Handle: '0'
  base: '0'
version: '1.01'
x_runtime:
  recommends: {}
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
